#################################################################################
#  Copyright (c) 2026 ARENA2036 e.V.
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################

---
# Default values for eclipse-dataspace-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

shared:
    connectorId: &connectorId did:web:wallet.int.construct-x.net:user
    secretAlias: &secretAlias usersecret
    trustedIssuerId: &trustedIssuerId did:web:issuer.int.construct-x.net:issuer
    clusterIssuer: &clusterIssuer letsencrypt-serv
    ingressClass: &ingressClass nginx
    imagePullSecret: &imagePullSecret registry-creds
    controlplaneFqdn: &controlplaneFqdn edc-controlplane.services.construct-x.net
    dataplaneFqdn: &dataplaneFqdn edc-dataplane.services.construct-x.net
    stsTokenUrl: &stsTokenUrl https://wallet.int.construct-x.net/api/sts/token
fullnameOverride: "edc"
nameOverride: "edc"

participant:
    id: &connectorId did:web:wallet.int.construct-x.net:user

iatp:
    id: *connectorId
    trustedIssuerId: &trustedIssuerId did:web:issuer.int.construct-x.net:issuer
    trustedIssuers:
        - id: *trustedIssuerId
    sts:
        oauth:
            token_url: *stsTokenUrl
            client:
                id: *connectorId
                secret_alias: *secretAlias
    didService:
        selfRegistration:
            id: *connectorId

controlplane:
    hostname: controlplane
    imagePullSecrets:
        - name: *imagePullSecret
    env:
        EDC_IAM_ISSUER_ID: *connectorId
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: *secretAlias
    ingresses:
        ## Public / Internet facing Ingress
        - enabled: true
          hostname: *controlplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *controlplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - protocol
          className: *ingressClass
          tls:
              enabled: true
              secretName: ""
          certManager:
              clusterIssuer: *clusterIssuer
        ## Private / Intranet facing Ingress
        - enabled: true                         # enabled for API testing
          hostname: *controlplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *controlplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - management
              - control
              - validation
              - metrics
          className: *ingressClass
          tls:
              enabled: true
              secretName: ""
          certManager:
              clusterIssuer: *clusterIssuer

dataplane:
    hostname: dataplane
    imagePullSecrets:
        - name: *imagePullSecret
    token:
        signer:
            privatekey_alias: prov_priv
        verifier:
            publickey_alias: prov_pub
    env:
        EDC_IAM_ISSUER_ID: *connectorId
        EDC_IAM_TRUSTED-ISSUER_EXAMPLE_ID: *trustedIssuerId
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: *secretAlias
    ingresses:
        ## Public / Internet facing Ingress
        - enabled: true
          hostname: *dataplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *dataplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - public
              - proxy
          className: *ingressClass
          tls:
              enabled: true
              secretName: ""
          certManager:
              clusterIssuer: *clusterIssuer
        ## Private / Intranet facing Ingress
        - enabled: true                         # enabled for API testing
          hostname: *dataplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *dataplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - management
              - control
              - metrics
          className: *ingressClass
          tls:
              enabled: true
              secretName: ""
          certManager:
              clusterIssuer: *clusterIssuer

postgresql:
    primary:
        persistence:
            enabled: true
    readReplicas:
        persistence:
            enabled: true
