nameOverride: provider-conn
participant:
    id: did:web:provider-idhub.staging.construct-x.net:provider
iatp:
    id: did:web:provider-idhub.staging.construct-x.net:provider
    trustedIssuerId: did:web:local-issuer-service.staging.construct-x.net:issuer
    trustedIssuers:
        - id: did:web:local-issuer-service.staging.construct-x.net:issuer
    sts:
        oauth:
            token_url: https://provider-idhub.staging.construct-x.net/api/sts/token
            client:
                id: did:web:provider-idhub.staging.construct-x.net:provider
                secret_alias: providersecret
    didService:
        selfRegistration:
            id: did:web:provider-idhub.staging.construct-x.net:provider
controlplane:
    nameOverride: provider-conn-controlplane
    enabled: true
    hostname: provider-conn-controlplane
    image:
        repository: registry.onstackit.cloud/constructx/con-x-controlplane-postgresql-hashicorp-vault
    imagePullSecrets:
        - name: registry-creds
    env:
        EDC_IAM_ISSUER_ID: did:web:provider-idhub.staging.construct-x.net:provider
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: providersecret
    ingresses:
        - enabled: true
          hostname: provider-conn-controlplane.staging.construct-x.net
          className: nginx
          annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
              external-dns.alpha.kubernetes.io/hostname: provider-conn-controlplane.staging.construct-x.net
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - default
              - management
              - public
              - protocol
              - validation
              - metrics
          tls:
              enabled: true
              secretName: provider-conn-cp-tls
          certManager:
              clusterIssuer: letsencrypt-staging
        - enabled: false
          hostname: provider-conn-controlplane.staging.construct-x.net
          endpoints:
              - control
          className: nginx
          tls:
              enabled: false
              secretName: "provider-conn-cp-tls"
          certManager:
              clusterIssuer: letsencrypt-staging
    url:
        control: https://provider-conn-controlplane.staging.construct-x.net/control
dataplane:
    nameOverride: provider-conn-dataplane
    enabled: true
    hostname: provider-conn-dataplane
    image:
        repository: registry.onstackit.cloud/constructx/con-x-dataplane-postgresql-hashicorp-vault
    imagePullSecrets:
        - name: registry-creds
    token:
        signer:
            privatekey_alias: prov_priv
        verifier:
            publickey_alias: prov_pub
    env:
        EDC_IAM_ISSUER_ID: did:web:provider-idhub.staging.construct-x.net:provider
        EDC_IAM_TRUSTED-ISSUER_EXAMPLE_ID: did:web:local-issuer-service.staging.construct-x.net:issuer
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: providersecret
    ingresses:
        - enabled: true
          hostname: provider-conn-dataplane.staging.construct-x.net
          className: nginx
          annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
              external-dns.alpha.kubernetes.io/hostname: provider-conn-dataplane.staging.construct-x.net
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - public
          tls:
              enabled: true
              secretName: provider-conn-dp-tls
          certManager:
              clusterIssuer: letsencrypt-staging
postgresql:
    primary:
        persistence:
            enabled: true
    readReplicas:
        persistence:
            enabled: true
