nameOverride: consumer-conn
participant:
    id: did:web:consumer-idhub.staging.construct-x.net:consumer
iatp:
    id: did:web:consumer-idhub.staging.construct-x.net:consumer
    trustedIssuerId: did:web:local-issuer-service.staging.construct-x.net:issuer
    trustedIssuers:
        - id: did:web:local-issuer-service.staging.construct-x.net:issuer
    sts:
        oauth:
            token_url: https://consumer-idhub.staging.construct-x.net/api/sts/token
            client:
                id: did:web:consumer-idhub.staging.construct-x.net:consumer
                secret_alias: consumersecret
    didService:
        selfRegistration:
            id: did:web:consumer-idhub.staging.construct-x.net:consumer
controlplane:
    nameOverride: consumer-conn-controlplane
    enabled: true
    hostname: consumer-conn-controlplane
    image:
        repository: registry.onstackit.cloud/constructx/con-x-controlplane-postgresql-hashicorp-vault
    imagePullSecrets:
        - name: registry-creds
    env:
        EDC_IAM_ISSUER_ID: did:web:consumer-idhub.staging.construct-x.net:consumer
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: consumersecret
    ingresses:
        - enabled: true
          hostname: consumer-conn-controlplane.staging.construct-x.net
          className: nginx
          annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
              external-dns.alpha.kubernetes.io/hostname: consumer-conn-controlplane.staging.construct-x.net
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - default
              - management
              - public
              - protocol
              - validation
              - metrics
          tls:
              enabled: true
              secretName: consumer-conn-cp-tls
          certManager:
              clusterIssuer: letsencrypt-staging
        - enabled: false
          hostname: consumer-conn-controlplane.staging.construct-x.net
          endpoints:
              - control
          className: nginx
          tls:
              enabled: false
          certManager:
              clusterIssuer: letsencrypt-staging
    url:
        control: https://consumer-conn-controlplane.staging.construct-x.net/control
dataplane:
    nameOverride: consumer-conn-dataplane
    enabled: true
    hostname: consumer-conn-dataplane
    image:
        repository: registry.onstackit.cloud/constructx/con-x-dataplane-postgresql-hashicorp-vault
    imagePullSecrets:
        - name: registry-creds
    token:
        signer:
            privatekey_alias: cons_priv
        verifier:
            publickey_alias: cons_pub
    env:
        EDC_IAM_ISSUER_ID: did:web:consumer-idhub.staging.construct-x.net:consumer
        EDC_IAM_TRUSTED-ISSUER_EXAMPLE_ID: did:web:local-issuer-service.staging.construct-x.net:issuer
        EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: consumersecret
    ingresses:
        - enabled: false
          hostname: consumer-conn-dataplane.staging.construct-x.net
          className: nginx
          annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
              external-dns.alpha.kubernetes.io/hostname: consumer-conn-dataplane.staging.construct-x.net
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - public
          tls:
              enabled: true
              secretName: consumer-conn-dp-tls
          certManager:
              clusterIssuer: letsencrypt-staging
postgresql:
    primary:
        persistence:
            enabled: true
    readReplicas:
        persistence:
            enabled: true
